version: '3'
services:
  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.3.0
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
  # Zipkin with memory storage / optionally enable kafka-based storage
  zipkin:
#    image: jeqo/zipkin-kafka:0.5.4
    image: openzipkin/zipkin:2.16.2
    ports:
      - 9411:9411
    environment:
      STORAGE_TYPE: mem
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    volumes:
#      - zipkin:/zipkin/data
#volumes:
#  zipkin:
